# Generated by Django 3.0 on 2019-12-20 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ItemMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('qty', models.FloatField()),
                ('total_amt', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ItemMaster.TblItemMaster')),
            ],
        ),
        migrations.CreateModel(
            name='TblStatusDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TblOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_amt', models.FloatField()),
                ('is_delivered', models.BooleanField()),
                ('is_approved', models.BooleanField()),
                ('is_rejected', models.BooleanField()),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Approved_Usr', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Customer_User', to=settings.AUTH_USER_MODEL)),
                ('delivery_boy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Db_User', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='OrderDetails.TblItemDetails')),
                ('status', models.ManyToManyField(to='OrderDetails.TblStatusDetails')),
            ],
        ),
    ]
