# Generated by Django 3.0 on 2019-12-10 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ItemMaster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('qty', models.FloatField()),
                ('total', models.FloatField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ItemMaster.TblItemMaster')),
            ],
        ),
        migrations.CreateModel(
            name='TblStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TblOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('total_amt', models.FloatField()),
                ('is_delivered', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DBoy_USER', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='OrderDetails.TblItemDetails')),
                ('status', models.ManyToManyField(to='OrderDetails.TblStatus')),
            ],
        ),
    ]
