# Generated by Django 3.0 on 2019-12-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluserdetails',
            name='UserType',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
