# Generated by Django 3.0 on 2020-01-02 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserDetails', '0004_tbluserdetails_is_approved'),
        ('ItemMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TblShopDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=300)),
                ('shop_address', models.CharField(max_length=400)),
                ('is_approved', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ShopDetails.TblLocation')),
                ('items', models.ManyToManyField(to='ItemMaster.TblItemMaster')),
                ('managers', models.ManyToManyField(related_name='UserManager', to='UserDetails.TblUserDetails')),
                ('super_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UserDetails.TblUserDetails')),
            ],
        ),
    ]
